// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/token/m2m_token.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/token/m2m_token.go -destination=mocks/domain/token/mock_m2m_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockM2MToken is a mock of M2MToken interface.
type MockM2MToken struct {
	ctrl     *gomock.Controller
	recorder *MockM2MTokenMockRecorder
	isgomock struct{}
}

// MockM2MTokenMockRecorder is the mock recorder for MockM2MToken.
type MockM2MTokenMockRecorder struct {
	mock *MockM2MToken
}

// NewMockM2MToken creates a new mock instance.
func NewMockM2MToken(ctrl *gomock.Controller) *MockM2MToken {
	mock := &MockM2MToken{ctrl: ctrl}
	mock.recorder = &MockM2MTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockM2MToken) EXPECT() *MockM2MTokenMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockM2MToken) AccessToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockM2MTokenMockRecorder) AccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockM2MToken)(nil).AccessToken))
}
